from pybatfish.datamodel.primitives import VariableType

COMPLETION_TYPES = [
    VariableType.ADDRESS_GROUP_NAME,
    VariableType.APPLICATION_SPEC,
    VariableType.BGP_PEER_PROPERTY_SPEC,
    VariableType.BGP_PROCESS_PROPERTY_SPEC,
    VariableType.BGP_SESSION_STATUS,
    VariableType.BGP_SESSION_TYPE,
    VariableType.DISPOSITION_SPEC,
    VariableType.FILTER,
    VariableType.FILTER_SPEC,
    VariableType.FLOW_STATE,
    VariableType.INTERFACE,
    VariableType.INTERFACE_GROUP_NAME,
    VariableType.INTERFACE_PROPERTY_SPEC,
    VariableType.IP,
    VariableType.IP_PROTOCOL_SPEC,
    VariableType.IP_SPACE_SPEC,
    VariableType.IPSEC_SESSION_STATUS,
    VariableType.LOCATION_SPEC,
    VariableType.MLAG_ID_SPEC,
    VariableType.NAMED_STRUCTURE_SPEC,
    VariableType.NODE_PROPERTY_SPEC,
    VariableType.NODE_ROLE_DIMENSION_NAME,
    VariableType.NODE_ROLE_NAME,
    VariableType.NODE_SPEC,
    VariableType.OSPF_PROPERTY_SPEC,
    VariableType.PREFIX,
    VariableType.PROTOCOL,
    VariableType.REFERENCE_BOOK_NAME,
    VariableType.ROUTING_PROTOCOL_SPEC,
    VariableType.STRUCTURE_NAME,
    VariableType.VRF,
    VariableType.ZONE
]
