channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - ipython=7.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pandoc=2.9.1.1
  - pip=20.0.2
  - python=3.7.4
  - readline=7.0
  - setuptools=45.1.0
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - attrs==19.3.0
    - babel==2.8.0
    - bidict==0.19.0
    - bleach==3.1.0
    - cerberus==1.3.2
    - chardet==3.0.4
    - commonmark==0.9.1
    - configargparse==0.15.2
    - decorator==4.4.1
    - deepdiff==4.0.9
    - defusedxml==0.6.0
    - docutils==0.16
    - entrypoints==0.3
    - idna==2.8
    - imagesize==1.2.0
    - inflection==0.3.1
    - ipaddress==1.0.23
    - ipython-genutils==0.2.0
    - jinja2==2.11.0
    - jsonpickle==1.2
    - jsonschema==3.2.0
    - jupyter-core==4.6.1
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - nbsphinx==0.5.0
    - netconan==0.11.0
    - ordered-set==3.1.1
    - packaging==20.1
    - pandocfilters==1.4.2
    - passlib==1.7.2
    - progressbar2==3.47.0
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - python-utils==2.3.0
    - pytz==2019.3
    - recommonmark==0.6.0
    - regex==2019.6.8
    - requests==2.22.0
    - six==1.14.0
    - snowballstemmer==2.0.0
    - sphinx==2.3.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - urllib3==1.25.8
    - webencodings==0.5.1
