name: Pre-commit
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 15-23 * * *'  # 8AM to 4PM Pacific; daily
    - cron: '0 0-1 * * *'    # 5PM to 6PM Pacific; daily


jobs:
  precommit:
    uses: ./.github/workflows/reusable-precommit.yml
    with:
      batfish_repo: 'batfish/batfish'
      batfish_ref: 'master'
    secrets:
      PYBATFISH_CODECOV_TOKEN: ${{ secrets.PYBATFISH_CODECOV_TOKEN }}
